/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registration;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nooby
 */
public class CourseRegFrame extends javax.swing.JFrame {

    /**
     * Creates new form CourseRegFrame
     */
    public CourseRegFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseBack = new javax.swing.JButton();
        btnCourseClear = new javax.swing.JButton();
        btnCourseSubmit = new javax.swing.JButton();
        tfCourseName = new javax.swing.JTextField();
        tfCourseDescription = new javax.swing.JTextField();
        tfCoursePrice = new javax.swing.JTextField();
        tfCoursePeriod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course registration");

        btnCourseBack.setText("Back");
        btnCourseBack.setPreferredSize(new java.awt.Dimension(68, 22));
        btnCourseBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseBackActionPerformed(evt);
            }
        });

        btnCourseClear.setText("Clear");
        btnCourseClear.setPreferredSize(new java.awt.Dimension(68, 22));
        btnCourseClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseClearActionPerformed(evt);
            }
        });

        btnCourseSubmit.setText("Submit");
        btnCourseSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseSubmitActionPerformed(evt);
            }
        });

        tfCourseName.setForeground(java.awt.Color.gray);
        tfCourseName.setText("Enter Course Name");
        tfCourseName.setToolTipText("");
        tfCourseName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfCourseName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCourseNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCourseNameFocusLost(evt);
            }
        });

        tfCourseDescription.setForeground(java.awt.Color.gray);
        tfCourseDescription.setText("Enter Course Description");
        tfCourseDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCourseDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCourseDescriptionFocusLost(evt);
            }
        });

        tfCoursePrice.setForeground(java.awt.Color.gray);
        tfCoursePrice.setText("Enter Course Price");
        tfCoursePrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCoursePriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCoursePriceFocusLost(evt);
            }
        });
        tfCoursePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCoursePriceActionPerformed(evt);
            }
        });

        tfCoursePeriod.setForeground(java.awt.Color.gray);
        tfCoursePeriod.setText("Enter Course Period");
        tfCoursePeriod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCoursePeriodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCoursePeriodFocusLost(evt);
            }
        });

        jLabel1.setText("Course Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnCourseSubmit)
                        .addGap(35, 35, 35)
                        .addComponent(btnCourseClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCourseBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfCourseDescription)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfCoursePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1)))
                .addGap(54, 88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCoursePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tfCourseDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tfCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseSubmit))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseClearActionPerformed
        if(DefaultName != null){
            tfCourseName.setForeground(Color.gray);
            tfCourseName.setText(DefaultName);
        }
        if(DefaultDescription != null){
            tfCourseDescription.setForeground(Color.gray);
            tfCourseDescription.setText(DefaultDescription);
        }
        if(DefaultPeriod != null){
            tfCoursePeriod.setForeground(Color.gray);
            tfCoursePeriod.setText(DefaultPeriod);
        }
        if(DefaultPrice != null){
            tfCoursePrice.setForeground(Color.gray);
            tfCoursePrice.setText(DefaultPrice);
        }
    }//GEN-LAST:event_btnCourseClearActionPerformed

    private void btnCourseSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseSubmitActionPerformed
        String inputName = null;
        String inputDescription = null;
        String inputPeriod = null;
        String inputPrice = null;
        if(!tfCourseName.getText().equals(DefaultName) && !tfCourseName.getText().equals("")){
            inputName = tfCourseName.getText();
            tfCourseName.setForeground(Color.gray);
            tfCourseName.setText(DefaultName);
        }
        if(!tfCourseDescription.getText().equals(DefaultDescription) && !tfCourseDescription.getText().equals("")){
            inputDescription = tfCourseDescription.getText();
            tfCourseDescription.setForeground(Color.gray);
            tfCourseDescription.setText(DefaultDescription);
        }
        if(!tfCoursePeriod.getText().equals(DefaultPeriod) && !tfCoursePeriod.getText().equals("")){
            inputPeriod = tfCoursePeriod.getText();
            tfCoursePeriod.setForeground(Color.gray);
            tfCoursePeriod.setText(DefaultPeriod);
        }
        if(!tfCoursePrice.getText().equals(DefaultPrice) && !tfCoursePrice.getText().equals("")){
            inputPrice = tfCoursePrice.getText();
            tfCoursePrice.setForeground(Color.gray);
            tfCoursePrice.setText(DefaultPrice);
        }
        conn = Registration.init();
        try {
            stmt = conn.createStatement();
            String insert = "Insert into Course_details(Course_Name , Course_Description, Course_Price, Course_Period) values ('"+inputName+"' , '"+inputDescription+"' , '"+inputPrice+"' , '"+inputPeriod+"')";
            PreparedStatement pst = conn.prepareStatement(insert);
            pst.execute();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(CourseRegFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnCourseSubmitActionPerformed

    private void btnCourseBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseBackActionPerformed
       dispose();
       new MenuFrame().setVisible(true);
    }//GEN-LAST:event_btnCourseBackActionPerformed

    private void tfCourseNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCourseNameFocusGained
        DefaultName = tfCourseName.getText();
        if(tfCourseName.getText().equals(DefaultName)){
            tfCourseName.setForeground(Color.black);
            tfCourseName.setText("");
        }
    }//GEN-LAST:event_tfCourseNameFocusGained

    private void tfCourseDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCourseDescriptionFocusGained
        DefaultDescription = tfCourseDescription.getText();
        if(tfCourseDescription.getText().equals(DefaultDescription)){
            tfCourseDescription.setForeground(Color.black);
            tfCourseDescription.setText("");
        }
    }//GEN-LAST:event_tfCourseDescriptionFocusGained

    private void tfCoursePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCoursePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCoursePriceActionPerformed

    private void tfCourseNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCourseNameFocusLost
        if(tfCourseName.getText().equals("")){
            tfCourseName.setForeground(Color.gray);
            tfCourseName.setText(DefaultName);
        }
    }//GEN-LAST:event_tfCourseNameFocusLost

    private void tfCourseDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCourseDescriptionFocusLost
        if(tfCourseDescription.getText().equals("")){
            tfCourseDescription.setForeground(Color.gray);
            tfCourseDescription.setText(DefaultDescription);
        }
    }//GEN-LAST:event_tfCourseDescriptionFocusLost

    private void tfCoursePeriodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCoursePeriodFocusGained
        DefaultPeriod = tfCoursePeriod.getText();
        if(tfCoursePeriod.getText().equals(DefaultPeriod)){
            tfCoursePeriod.setForeground(Color.black);
            tfCoursePeriod.setText("");
        }
    }//GEN-LAST:event_tfCoursePeriodFocusGained

    private void tfCoursePeriodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCoursePeriodFocusLost
        if(tfCoursePeriod.getText().equals("")){
            tfCoursePeriod.setForeground(Color.gray);
            tfCoursePeriod.setText(DefaultPeriod);
        }
    }//GEN-LAST:event_tfCoursePeriodFocusLost

    private void tfCoursePriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCoursePriceFocusGained
        DefaultPrice = tfCoursePrice.getText();
        if(tfCoursePrice.getText().equals(DefaultPrice)){
            tfCoursePrice.setForeground(Color.black);
            tfCoursePrice.setText("");
        }
    }//GEN-LAST:event_tfCoursePriceFocusGained

    private void tfCoursePriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCoursePriceFocusLost
        if(tfCoursePrice.getText().equals("")){
            tfCoursePrice.setForeground(Color.gray);
            tfCoursePrice.setText(DefaultPrice);
        }
    }//GEN-LAST:event_tfCoursePriceFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseRegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseRegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseRegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseRegFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseRegFrame().setVisible(true);
                
            }
        });
    }
    //New Varivles Declaration
    Connection conn;
    Statement stmt;
    String DefaultName;
    String DefaultDescription;
    String DefaultPrice;
    String DefaultPeriod;
    // End of Variable Declaration
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseBack;
    private javax.swing.JButton btnCourseClear;
    private javax.swing.JButton btnCourseSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfCourseDescription;
    private javax.swing.JTextField tfCourseName;
    private javax.swing.JTextField tfCoursePeriod;
    private javax.swing.JTextField tfCoursePrice;
    // End of variables declaration//GEN-END:variables
}
